repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
        exclude_types: [sh]
    -   id: end-of-file-fixer
        exclude_types: [sh]
    - id: check-merge-conflict
    - id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black-jupyter
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
    - id: nbstripout
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
